[package]
name = "ws"
version = "0.1.0"
authors = ["Jason Housley <HousleyJK@gmail.com>"]

[dependencies]
mio = "0.4.2"
log = "0.3.1"
httparse = "0.1.6"
sha1 = "0.1.1"
rand = "0.3.10"
url = "0.2.37"

[dev-dependencies]
env_logger = "0.3.1"
clock_ticks = "0.0.6"
