[package]
name = "ws"
version = "0.2.0"
authors = ["Jason Housley <HousleyJK@gmail.com>"]

description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
repository = "https://github.com/housleyjk/ws-rs"
readme = "README.md"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"

[dependencies]
mio = "0.4.3"
log = "0.3.2"
httparse = "0.1.6"
sha1 = "0.1.1"
rand = "0.3.11"
url = "0.2.37"

[dev-dependencies]
env_logger = "0.3.1"
clock_ticks = "0.0.6"
