[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"
name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.5.0"

[dependencies]
httparse = "1.1.2"
log = "0.3.6"
mio = { git = "https://github.com/ethcore/mio", branch = "v0.5.x" }
rand = "0.3.14"
sha1 = "0.1.1"
url = "1.1.1"

[dependencies.libc]
optional = true
version = "0.2.12"

[dependencies.libz-sys]
optional = true
version = "1.0.4"

[dependencies.openssl]
optional = true
version = "0.7.13"

[dev-dependencies]
clap = "2.6.0"
env_logger = "0.3.3"
term = "0.4.4"
time = "0.1.35"

[features]
default = []
permessage-deflate = ["libz-sys", "libc"]
ssl = ["openssl"]
