[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"
name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.5.0"

[dependencies]
httparse = "*"
log = "*"
mio = "*"
rand = "*"
sha1 = "*"
url = "*"
openssl = { version = "*", optional = true }
libz-sys = { version = "*", optional = true }
libc = { version = "*", optional = true }

[dev-dependencies]
clap = "*"
env_logger = "*"
term = "*"
time = "*"

[features]
default = []
permessage-deflate = ["libz-sys", "libc"]
ssl = ["openssl"]
