[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"
name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.4.6"

[dependencies]
httparse = "*"
log = "*"
mio = { version = "*", git = "https://github.com/carllerche/mio.git" }
openssl = { version = "*", optional = true }
rand = "*"
sha1 = "*"
url = "*"
slab = "*"

[dev-dependencies]
clap = "2.2.1"
env_logger = "0.3.2"
term = "0.4.4"
time = "0.1.34"

[features]
default = []
ssl = ["openssl"]
